mmi_blog:
    resource: "@MmiBlogBundle/Controller/"
    type:     annotation
<<<<<<< HEAD
    prefix:   /
=======
    prefix:   /blog
>>>>>>> projet_original_master/master

mmi_bootstrap:
    resource: "@MmiBootstrapBundle/Controller/"
    type:     annotation
    prefix:   /bootstrap

mmi_hello:
    resource: "@MmiHelloBundle/Controller/"
    type:     annotation
    prefix:   /hello